# Generated by Django 5.1.1 on 2024-10-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wesite',
            field=models.URLField(blank=True, null=True),
        ),
    ]
